/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithdrawIdRouteImport } from './routes/withdraw.$id'
import { Route as TaskSlugRouteImport } from './routes/task.$slug'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminTasksTypeRouteImport } from './routes/admin.tasks.$type'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawIdRoute = WithdrawIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WithdrawRoute,
} as any)
const TaskSlugRoute = TaskSlugRouteImport.update({
  id: '/task/$slug',
  path: '/task/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksTypeRoute = AdminTasksTypeRouteImport.update({
  id: '/tasks/$type',
  path: '/tasks/$type',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRoute
  '/task/$slug': typeof TaskSlugRoute
  '/withdraw/$id': typeof WithdrawIdRoute
  '/admin/tasks/$type': typeof AdminTasksTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRoute
  '/task/$slug': typeof TaskSlugRoute
  '/withdraw/$id': typeof WithdrawIdRoute
  '/admin/tasks/$type': typeof AdminTasksTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/profile': typeof ProfileRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/wallet': typeof WalletRoute
  '/withdraw': typeof WithdrawRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRoute
  '/task/$slug': typeof TaskSlugRoute
  '/withdraw/$id': typeof WithdrawIdRoute
  '/admin/tasks/$type': typeof AdminTasksTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/help'
    | '/profile'
    | '/referral'
    | '/register'
    | '/wallet'
    | '/withdraw'
    | '/admin/referrals'
    | '/task/$slug'
    | '/withdraw/$id'
    | '/admin/tasks/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/help'
    | '/profile'
    | '/referral'
    | '/register'
    | '/wallet'
    | '/withdraw'
    | '/admin/referrals'
    | '/task/$slug'
    | '/withdraw/$id'
    | '/admin/tasks/$type'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/help'
    | '/profile'
    | '/referral'
    | '/register'
    | '/wallet'
    | '/withdraw'
    | '/admin/referrals'
    | '/task/$slug'
    | '/withdraw/$id'
    | '/admin/tasks/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  ProfileRoute: typeof ProfileRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  WalletRoute: typeof WalletRoute
  WithdrawRoute: typeof WithdrawRouteWithChildren
  TaskSlugRoute: typeof TaskSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw/$id': {
      id: '/withdraw/$id'
      path: '/$id'
      fullPath: '/withdraw/$id'
      preLoaderRoute: typeof WithdrawIdRouteImport
      parentRoute: typeof WithdrawRoute
    }
    '/task/$slug': {
      id: '/task/$slug'
      path: '/task/$slug'
      fullPath: '/task/$slug'
      preLoaderRoute: typeof TaskSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks/$type': {
      id: '/admin/tasks/$type'
      path: '/tasks/$type'
      fullPath: '/admin/tasks/$type'
      preLoaderRoute: typeof AdminTasksTypeRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminTasksTypeRoute: typeof AdminTasksTypeRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReferralsRoute: AdminReferralsRoute,
  AdminTasksTypeRoute: AdminTasksTypeRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WithdrawRouteChildren {
  WithdrawIdRoute: typeof WithdrawIdRoute
}

const WithdrawRouteChildren: WithdrawRouteChildren = {
  WithdrawIdRoute: WithdrawIdRoute,
}

const WithdrawRouteWithChildren = WithdrawRoute._addFileChildren(
  WithdrawRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  ProfileRoute: ProfileRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  WalletRoute: WalletRoute,
  WithdrawRoute: WithdrawRouteWithChildren,
  TaskSlugRoute: TaskSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
